// app/components/pages/add/AddRentData.vue
<script setup lang="ts">
import { ref, computed, onMounted, nextTick } from 'vue';
import { useAuth } from '~/composables/useAuth';
import { get_utc_date, normaliseDate, MONTH_NAMES } from '~/tools/date';
import { Label } from '~/components/ui/label';
import { Input } from '~/components/ui/input';
import { Button } from '~/components/ui/button';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle
} from '~/components/ui/alert-dialog';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';

const { isAdmin } = useAuth();
const { $client } = useNuxtApp();

const todaysDate = new Date();
const currentMonth = todaysDate.getMonth() + 1;
const currentYear = todaysDate.getFullYear();

const getTodaysDate = () => {
  const prefixZeros = (n: number) => `${n < 10 ? '0' : ''}${n}`;
  return `${currentYear}-${prefixZeros(currentMonth)}-${prefixZeros(todaysDate.getDate())}`;
};

// Form state
const date = ref(getTodaysDate());
const month = ref((currentMonth === 1 ? 12 : currentMonth - 1).toString());
const year = ref((currentMonth === 1 ? currentYear - 1 : currentYear).toString());
const amount = ref('');
const rentType = ref<'rent' | 'electricity'>('rent');

// UI state
const amountInputElement = ref<HTMLInputElement | null>(null);
const confirmDialogOpen = ref(false);
const isLoading = ref(false);
const isSuccess = ref(false);
const successData = ref<any>(null);

// tRPC mutation
const submitDataMutation = async () => {
  const amountNum = parseInt(amount.value);
  if (
    !date.value ||
    date.value === '' ||
    !amount.value ||
    amount.value === '' ||
    isNaN(amountNum) ||
    amountNum === 0
  )
    return;

  isLoading.value = true;

  try {
    const data = await $client.data.add_data.mutate({
      data: {
        rent_type: rentType.value,
        date: get_utc_date(date.value),
        amount: amountNum,
        month: get_utc_date(`${year.value}-${month.value}-1`)
      }
    });

    isSuccess.value = true;
    successData.value = data;
  } catch (error) {
    console.error('Error submitting data:', error);
  } finally {
    isLoading.value = false;
    confirmDialogOpen.value = false;
  }
};

const submitForm = (e: Event) => {
  e.preventDefault();
  const amountNum = parseInt(amount.value);
  if (
    !date.value ||
    date.value === '' ||
    !amount.value ||
    amount.value === '' ||
    isNaN(amountNum) ||
    amountNum === 0
  )
    return;
  confirmDialogOpen.value = true;
};

const resetForm = async () => {
  date.value = getTodaysDate();
  month.value = currentMonth.toString();
  year.value = currentYear.toString();
  amount.value = '';
  isSuccess.value = false;
  successData.value = null;

  await nextTick();
  if (amountInputElement.value) {
    amountInputElement.value.focus();
  }
};

onMounted(() => {
  if (amountInputElement.value) {
    amountInputElement.value.focus();
  }
});

const yearOptions = computed(() => [
  (currentYear - 1).toString(),
  currentYear.toString(),
  (currentYear + 1).toString()
]);

const monthName = computed(() => MONTH_NAMES[parseInt(month.value) - 1]);
</script>

<template>
  <div>
    <!-- Success State -->
    <div v-if="isSuuccess && successData?.status === 'success'" class="space-y-3">
      <NuxtLink
        to="/"
        class="bg-primary text-primary-foreground hover:bg-primary/90 inline-flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium"
      >
        <Icon name="lucide:home" class="h-4 w-4" />
        Home Page
      </NuxtLink>

      <div class="font-semibold">
        Successfully Added Record of ₹ {{ amount }} dated {{ normaliseDate(date) }}.
      </div>

      <Button variant="secondary" @click="resetForm" class="gap-2">
        <Icon name="lucide:plus" class="h-4 w-4" />
        Add More
      </Button>
    </div>

    <!-- Form -->
    <form v-else @submit="submitForm" class="space-y-4">
      <!-- Rent Type Selection (Admin only) -->
      <div v-if="isAdmin" class="space-y-3">
        <Label>Type</Label>
        <div class="flex space-x-6">
          <RadioGroup v-model="rentType" class="flex items-center justify-center space-x-4">
            <div class="flex items-center space-x-2">
              <RadioGroupItem id="rent" value="rent" />
              <Label for="rent">
                <Icon name="lucide:home" class="size-4" />
                Rent
              </Label>
            </div>
            <div class="flex items-center space-x-2">
              <RadioGroupItem id="electricity" value="electricity" />
              <Label for="electricity">
                <Icon name="lucide:zap" class="size-4" />
                Electricity
              </Label>
            </div>
          </RadioGroup>
        </div>
      </div>

      <!-- Date Input -->
      <div class="space-y-2">
        <Label for="date">Date</Label>
        <Input id="date" v-model="date" type="date" required />
      </div>

      <!-- Month Selection -->
      <div class="space-y-2">
        <Label for="month">Month</Label>
        <select
          v-model="month"
          id="month"
          class="focus:border-primary focus:ring-primary dark:focus:border-primary dark:focus:ring-primary block w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-base text-gray-900 shadow-sm transition-colors focus:ring-2 focus:outline-none dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100"
        >
          <option
            v-for="(monthName, index) in MONTH_NAMES"
            :key="index"
            :value="(index + 1).toString()"
            class="bg-white text-gray-900 dark:bg-gray-900 dark:text-gray-100"
          >
            {{ monthName }}
          </option>
        </select>
      </div>

      <!-- Year Selection -->
      <div class="space-y-2">
        <Label for="year">Year</Label>
        <select
          v-model="year"
          id="year"
          class="focus:border-primary focus:ring-primary dark:focus:border-primary dark:focus:ring-primary block w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-base text-gray-900 shadow-sm transition-colors focus:ring-2 focus:outline-none dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100"
        >
          <option
            v-for="yearOption in yearOptions"
            :key="yearOption"
            :value="yearOption"
            class="bg-white text-gray-900 dark:bg-gray-900 dark:text-gray-100"
          >
            {{ yearOption }}
          </option>
        </select>
      </div>

      <!-- Amount Input -->
      <div class="space-y-2">
        <Label for="amount">Amount</Label>
        <Input
          id="amount"
          ref="amountInputElement"
          v-model="amount"
          type="number"
          placeholder="Amount"
          required
          :min="100"
        />
      </div>

      <!-- Submit Button -->
      <Button type="submit" :disabled="isLoading" class="gap-2 font-bold">
        <Icon name="lucide:plus" class="h-4 w-4" />
        Add Record
      </Button>
    </form>

    <!-- Confirmation Dialog -->
    <AlertDialog v-model:open="confirmDialogOpen">
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>Are you sure to Add?</AlertDialogTitle>
          <AlertDialogDescription as-child>
            <div class="flex items-center gap-2">
              <span>₹ {{ amount }}</span>
              <Icon name="lucide:arrow-right" class="h-4 w-4" />
              <span class="font-bold">{{ monthName }} {{ year }}</span>
            </div>
          </AlertDialogDescription>
        </AlertDialogHeader>

        <AlertDialogFooter>
          <AlertDialogCancel>Cancel</AlertDialogCancel>
          <AlertDialogAction @click="submitDataMutation" :disabled="isLoading">
            <Icon v-if="isLoading" name="lucide:loader-2" class="mr-2 h-4 w-4 animate-spin" />
            Confirm
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  </div>
</template>

// src/app/add/AddRentData.tsx
'use client';

import { useContext, useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import { AppContext } from '~/state/AppDataContext';
import { api } from '$convex/_generated/api';
import { useMutation } from 'convex/react';
import { MONTH_NAMES, normaliseDate } from '~/tools/date';
import { Button } from '~/components/ui/button';
import { Input } from '~/components/ui/input';
import { Label } from '~/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from '~/components/ui/select';
import { RadioGroup, RadioGroupItem } from '~/components/ui/radio-group';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle
} from '~/components/ui/alert-dialog';
import { Home, Zap, Plus } from 'lucide-react';
import AuthenticatePassword from './AuthenticatePassword';
import UserControls from './UserControls';
import { TiArrowRightOutline } from 'react-icons/ti';

type RentType = 'rent' | 'electricity';
type Status = 'idle' | 'confirm' | 'submitting' | 'success' | 'error';

const getTodayDateString = () => {
  const d = new Date();
  const yyyy = d.getFullYear();
  const mm = `${d.getMonth() + 1}`.padStart(2, '0');
  const dd = `${d.getDate()}`.padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
};

export default function AddRentData() {
  const { user_info } = useContext(AppContext);

  const today = new Date();
  // const initialMonthNum = today.getMonth() + 1;
  const initialMonthNum = (() => {
    const mn = today.getMonth() + 1;
    const prev = mn === 1 ? 12 : mn - 1;
    return prev;
  })();
  // const initialYearNum = today.getFullYear();
  const initialYearNum = (() => {
    const yr = today.getFullYear();
    const prev = Number(initialMonthNum) === 1 ? yr - 1 : yr;
    return prev;
  })();

  const [month, setMonth] = useState<string>(initialMonthNum.toString());
  const [year, setYear] = useState<string>(initialYearNum.toString());
  const [date, setDate] = useState<string>(getTodayDateString());
  const [amount, setAmount] = useState<number | null>(null);
  const [rentType, setRentType] = useState<RentType>('rent');

  // Single status to represent mutation and UI flow
  const [status, setStatus] = useState<Status>('idle');

  const addRentData = useMutation(api.routes.addEditData.addRentData);

  const amountInputRef = useRef<HTMLInputElement>(null);
  useEffect(() => {
    amountInputRef.current?.focus();
  }, []);

  const resetForm = () => {
    setDate(getTodayDateString());
    setMonth(String(initialMonthNum));
    setYear(String(initialYearNum));
    setAmount(null);
    setRentType('rent');
    setStatus('idle');
    setTimeout(() => amountInputRef.current?.focus(), 200);
  };

  const handleSubmitConfirmed = async () => {
    if (!date || amount === null || Number(amount) <= 0) return;
    const payload = {
      rent_type: rentType,
      date, // by default in yyyy-mm-dd format
      amount: Number(amount),
      month: `${year}-${String(month).padStart(2, '0')}`
    } as const;
    try {
      setStatus('submitting');
      await addRentData(payload);
      setStatus('success');
    } catch (err: any) {
      // Keep generic error to avoid separate error message state
      setStatus('error');
    }
  };

  if (!user_info) return <AuthenticatePassword />;

  return (
    <div className="space-y-4">
      <div className="flex items-end justify-end">
        <UserControls />
      </div>

      {status !== 'success' && (
        <form
          className="space-y-3"
          onSubmit={(e) => {
            e.preventDefault();
            if (!date || amount === null || Number(amount) < 100) return;
            setStatus('confirm');
          }}
        >
          {user_info?.role === 'admin' && (
            <RadioGroup
              className="flex gap-6"
              value={rentType}
              onValueChange={(v) => setRentType(v as RentType)}
            >
              <Label className="flex cursor-pointer items-center gap-2">
                <RadioGroupItem value="rent" />
                <Home className="size-5 text-sky-600 dark:text-sky-400" />
                Rent
              </Label>
              <Label className="flex cursor-pointer items-center gap-2">
                <RadioGroupItem value="electricity" id="rt_elec" />
                <Zap className="size-5 text-yellow-600 dark:text-yellow-400" />
                Electricity
              </Label>
            </RadioGroup>
          )}

          <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
            <div className="flex flex-col gap-1">
              <Label htmlFor="date">Date</Label>
              <Input
                id="date"
                type="date"
                required
                value={date}
                onChange={(e) => setDate(e.target.value)}
              />
            </div>

            <div className="flex flex-col gap-1">
              <Label>Month</Label>
              <Select value={month} onValueChange={setMonth}>
                <SelectTrigger>
                  <SelectValue placeholder="Select month" />
                </SelectTrigger>
                <SelectContent>
                  {MONTH_NAMES.map((mn, i) => (
                    <SelectItem key={mn} value={`${i + 1}`}>
                      {mn}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="flex flex-col gap-1">
              <Label>Year</Label>
              <Select value={year} onValueChange={setYear}>
                <SelectTrigger>
                  <SelectValue placeholder="Select year" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value={`${initialYearNum - 1}`}>{initialYearNum - 1}</SelectItem>
                  <SelectItem value={`${initialYearNum}`}>{initialYearNum}</SelectItem>
                  <SelectItem value={`${initialYearNum + 1}`}>{initialYearNum + 1}</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="flex flex-col gap-1">
            <Label htmlFor="amount">Amount</Label>
            <Input
              id="amount"
              type="number"
              min={100}
              required
              value={amount ?? ''}
              onChange={(e) => setAmount(e.target.value === '' ? null : Number(e.target.value))}
              ref={amountInputRef}
              placeholder="Amount"
            />
          </div>

          {status === 'error' && <div className="text-sm text-red-600">Failed to add record</div>}

          <Button
            type="submit"
            disabled={status === 'submitting'}
            className="mt-2 inline-flex items-center gap-2 text-base font-semibold"
          >
            {status === 'submitting' ? (
              'Adding...'
            ) : (
              <>
                <Plus className="size-5" />
                Add Record
              </>
            )}
          </Button>
        </form>
      )}

      {status === 'success' && (
        <div className="space-y-2">
          <Link href="/" className="inline-flex">
            <Button variant="default" className="gap-2" type="button">
              Home Page
            </Button>
          </Link>
          <div className="font-semibold">
            Successfully Added Record of ₹ {amount!} dated {normaliseDate(date)}.
          </div>
          <Button
            variant="secondary"
            type="button"
            onClick={() => {
              resetForm();
            }}
          >
            Add More
          </Button>
        </div>
      )}

      <AlertDialog
        open={status === 'confirm'}
        onOpenChange={(open) => setStatus(open ? 'confirm' : 'idle')}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Are you sure to Add?</AlertDialogTitle>
            <AlertDialogDescription className="flex items-center gap-2 select-none">
              ₹ {amount!} <TiArrowRightOutline className="size-4" />{' '}
              {MONTH_NAMES[parseInt(month) - 1]} {year}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={status === 'submitting'}>Cancel</AlertDialogCancel>
            <AlertDialogAction
              disabled={status === 'submitting'}
              onClick={async () => {
                await handleSubmitConfirmed();
              }}
              className="font-bold"
            >
              Confirm
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
