// app/components/pages/add/AuthenticatePassword.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { get_id_token_info, storeAuthInfo } from '~/tools/auth_tools';
import { Input } from '~/components/ui/input';
import { Button } from '~/components/ui/button';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from '~/components/ui/select';
import { cn } from '~/lib/utils';
import { useMutation } from '@tanstack/vue-query';

interface User {
  id: number;
  name: string;
}

interface Props {
  usersData: User[];
}

const props = defineProps<Props>();
const { $client } = useNuxtApp();
const { user_info } = useAuth();

const selectedUserId = ref<string | undefined>(undefined);
const password = ref('');
const wrongPassStatus = ref(false);
const passInputElement = ref<HTMLInputElement>();

// Auto-hide wrong password status after 1 second
watch(wrongPassStatus, (newVal) => {
  if (newVal) {
    setTimeout(() => {
      wrongPassStatus.value = false;
    }, 1000);
  }
});

const { isPending, mutate } = useMutation({
  mutationFn: $client.auth.verify_pass.mutate,
  onSuccess(data) {
    if (!data.verified) {
      password.value = '';
      passInputElement.value?.focus();
      wrongPassStatus.value = true;
    } else {
      storeAuthInfo(data);
      user_info.value = get_id_token_info().user;
    }
  },
  onError(error) {
    console.error('Authentication error:', error);
    wrongPassStatus.value = true;
  }
});

const check_password_func = async (e: Event) => {
  e.preventDefault();
  if (!selectedUserId.value || password.value === '' || isPending.value) return;

  mutate({
    id: parseInt(selectedUserId.value),
    password: password.value
  });
};
</script>

<template>
  <div class="text-lg font-bold text-orange-600 dark:text-yellow-500">Authentication</div>

  <form @submit.prevent="check_password_func" class="mt-2 space-y-2.5">
    <div class="space-y-2">
      <Select v-model="selectedUserId">
        <SelectTrigger class="font-bold">
          <SelectValue :placeholder="'Select user...'" />
        </SelectTrigger>
        <SelectContent>
          <SelectItem
            v-for="user in usersData"
            :key="user.id"
            :value="user.id.toString()"
            class="font-semibold"
          >
            {{ user.id }} → {{ user.name }}
          </SelectItem>
        </SelectContent>
      </Select>
    </div>

    <div class="space-y-2">
      <Input
        id="password"
        ref="passInputElement"
        v-model="password"
        type="password"
        placeholder="गूढपद"
        required
        :class="cn('w-full', wrongPassStatus && 'border-red-500 bg-red-50 dark:bg-red-950')"
      />
    </div>

    <Button type="submit" :disabled="isPending" class="gap-2 px-4 py-1 font-semibold">
      <Icon v-if="isPending" name="lucide:loader-2" class="h-4 w-4 animate-spin" />
      Submit
    </Button>
  </form>
</template>

// src/components/AuthenticatePassword.svelte
<script lang="ts">
  import { client_q } from '~/api/client';
  import Spinner from './Spinner.svelte';
  import { cl_join } from '~/tools/cl_join';
  import { get_id_token_info, storeAuthInfo } from '~/tools/auth_tools';
  import { user_info } from '~/state/user.svelte';

  let {
    pass_input_element = $bindable(),
    users_data
  }: {
    on_verify?: (verified: boolean, jwt_token: string) => void;
    pass_input_element?: HTMLInputElement;
    users_data: {
      id: number;
      name: string;
    }[];
  } = $props();

  let user_id = $state(1); // 1st user(admin)
  let password = $state('');

  const pass_verify = client_q.auth.verify_pass.mutation({
    onSuccess(data) {
      if (!data.verified) {
        password = '';
        pass_input_element && pass_input_element.focus();
        wrong_pass_status = true;
      } else {
        storeAuthInfo(data);
        $user_info = get_id_token_info().user;
      }
    }
  });

  let wrong_pass_status = $state(false);
  $effect(() => {
    wrong_pass_status && setTimeout(() => (wrong_pass_status = false), 1000);
  });

  const check_pass_func = async (e: Event) => {
    e.preventDefault();
    if (password === '') return;
    $pass_verify.mutate({ id: user_id, password });
  };
</script>

<div class="font-bold text-orange-600 dark:text-yellow-500">Authentication</div>
<form onsubmit={check_pass_func} class="mt-2 space-y-2.5">
  <select bind:value={user_id} class="select rounded-xl font-bold select-none">
    {#each users_data as user}
      <option value={user.id} class="font-semibold">
        {user.id}
        →
        {user.name}
      </option>
    {/each}
  </select>
  <input
    class={cl_join('input', wrong_pass_status && 'preset-tonal-error')}
    type="password"
    bind:value={password}
    placeholder="गूढपद"
    required
    bind:this={pass_input_element}
  />
  <button
    type="submit"
    class="btn preset-filled-primary-400-600 gap-0 rounded-lg py-1 pr-4 pl-0 font-semibold"
  >
    <Spinner show={$pass_verify.isPending} />
    Submit
  </button>
</form>
