// app/components/ThemeChanger.vue
<template>
  <div class="flex items-center space-x-2">
    <Button
      variant="ghost"
      size="icon"
      @click="() => (colorMode.preference = 'system')"
      :class="['group h-8 w-8', colorMode.preference === 'system' ? 'bg-accent' : '']"
    >
      <Icon
        name="lucide:monitor"
        class="h-4 w-4 group-hover:text-blue-500 dark:group-hover:text-sky-500"
      />
    </Button>

    <Button
      variant="ghost"
      size="icon"
      @click="() => (colorMode.preference = 'light')"
      :class="['group h-8 w-8', colorMode.preference === 'light' ? 'bg-accent' : '']"
    >
      <Icon name="lucide:sun" class="h-4 w-4 group-hover:text-yellow-500" />
    </Button>

    <Button
      variant="ghost"
      size="icon"
      @click="() => (colorMode.preference = 'dark')"
      :class="['group h-8 w-8', colorMode.preference === 'dark' ? 'bg-accent' : '']"
    >
      <Icon
        name="lucide:moon"
        class="h-4 w-4 group-hover:text-purple-600 dark:group-hover:text-white"
      />
    </Button>
  </div>
</template>

<script setup lang="ts">
import { Button } from '~/components/ui/button';

const colorMode = useColorMode();
</script>

// src/components/ThemeChanger.svelte
<script lang="ts">
  import { setMode } from 'mode-watcher';
  import { LuSun, LuMoon } from 'svelte-icons-pack/lu';
  import Icon from '@tools/Icon.svelte';
  import { SlScreenDesktop } from 'svelte-icons-pack/sl';
</script>

<button
  class="btn-xl group -mb-1 ml-0 mr-0 inline-flex items-center p-0"
  on:click={() => setMode('system')}
>
  <Icon
    src={SlScreenDesktop}
    class="h-5 w-5 rotate-0 scale-100 group-hover:text-blue-500 dark:group-hover:text-sky-500"
  />
</button>
<button
  class="btn-xl group -mb-1 ml-0 mr-0 inline-flex items-center p-0"
  on:click={() => setMode('light')}
>
  <Icon src={LuSun} class="h-5 w-5 rotate-0 scale-100 dark:group-hover:text-yellow-300" />
</button>
<button
  class="btn-xl group -mb-1 ml-0 mr-0 inline-flex items-center p-0"
  on:click={() => setMode('dark')}
>
  <Icon
    src={LuMoon}
    class="h-5 w-5 rotate-0 scale-100 group-hover:text-purple-600 dark:group-hover:text-white"
  />
</button>
