// src/components/UserControls.svelte
<script lang="ts">
  import { Popover, Modal } from '@skeletonlabs/skeleton-svelte';
  import Icon from '~/tools/Icon.svelte';
  import { BiLogOut } from 'svelte-icons-pack/bi';
  import { deleteAuthCookies } from '~/tools/auth_tools';
  import { user_info } from '~/state/user.svelte';
  import { VscAccount } from 'svelte-icons-pack/vsc';
  import { AiOutlineUser } from 'svelte-icons-pack/ai';

  let user_info_popover_status = $state(false);
  let logout_modal_status = $state(false);
  const log_out = () => {
    deleteAuthCookies();
    logout_modal_status = false;
    $user_info = null;
  };
</script>

<Popover
  open={user_info_popover_status}
  onOpenChange={(e) => (user_info_popover_status = e.open)}
  triggerBase="btn m-2 p-0 select-none outline-none"
  contentBase="card z-40 pt-1 px-1 shadow-2xl bg-surface-100-900 rounded-lg"
  positioning={{ placement: 'left-start' }}
>
  {#snippet trigger()}
    <Icon class="hover:text-gray-6200 text-3xl dark:hover:text-gray-400" src={VscAccount} />
  {/snippet}
  {#snippet content()}
    <div class="space-y-2 p-1 select-none">
      <div class="text-center text-base font-bold">
        <Icon class="-mt-1 text-2xl" src={AiOutlineUser} />
        {$user_info!.name}
        <span class="text-sm text-gray-500 dark:text-gray-400">(#{$user_info!.id})</span>
      </div>
      <div class="space-y-2 p-1 select-none">
        <Modal
          open={logout_modal_status}
          onOpenChange={(e) => (logout_modal_status = e.open)}
          contentBase="card z-50 space-y-2 rounded-lg px-3 py-2 shadow-xl bg-surface-100-900"
          backdropBackground="backdrop-blur-sm"
        >
          {#snippet trigger()}
            <span
              class="btn bg-error-600 m-0 gap-1 rounded-md pt-0 pr-2 pb-1 pl-1 font-bold text-white"
            >
              <Icon class="text-2xl" src={BiLogOut} />
              <span>Logout</span>
            </span>
          {/snippet}
          {#snippet content()}
            <div class="text-lg font-bold">Are you sure to logout ?</div>
            <div class="space-x-2">
              <button
                class="btn preset-filled-surface-300-700 rounded-lg font-semibold"
                onclick={log_out}
              >
                Confirm
              </button>
              <button
                onclick={() => (logout_modal_status = false)}
                class="btn preset-outlined-surface-800-200 rounded-lg font-semibold"
              >
                Cancel
              </button>
            </div>
          {/snippet}
        </Modal>
      </div>
    </div>
  {/snippet}
</Popover>

// app/components/pages/add/UserControls.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useAuth } from '~/composables/useAuth';
import { deleteAuthCookies } from '~/tools/auth_tools';
import { Button } from '~/components/ui/button';
import { Popover, PopoverContent, PopoverTrigger } from '~/components/ui/popover';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger
} from '~/components/ui/alert-dialog';

const { user_info } = useAuth();
const userInfoPopoverOpen = ref(false);
const logoutDialogOpen = ref(false);

const logOut = async () => {
  deleteAuthCookies();
  logoutDialogOpen.value = false;
  userInfoPopoverOpen.value = false;
  user_info.value = null;
};
</script>

<template>
  <Popover v-model:open="userInfoPopoverOpen">
    <PopoverTrigger as-child>
      <Button
        variant="ghost"
        size="icon"
        class="h-10 w-10 outline-none select-none hover:text-gray-600 dark:hover:text-gray-400"
      >
        <Icon name="lucide:user" class="h-6 w-6" />
      </Button>
    </PopoverTrigger>

    <PopoverContent class="w-64 p-2" align="end">
      <div class="space-y-2 select-none">
        <!-- User Info -->
        <div class="border-b pb-2 text-center">
          <div class="flex items-center justify-center gap-2 text-base font-bold">
            <Icon name="lucide:user" class="h-5 w-5" />
            {{ user_info?.name }}
          </div>
          <div class="text-sm text-gray-500 dark:text-gray-400">#{{ user_info?.id }}</div>
        </div>

        <!-- Logout Button -->
        <div class="pt-1">
          <AlertDialog v-model:open="logoutDialogOpen">
            <AlertDialogTrigger as-child>
              <Button variant="destructive" class="w-full gap-2 font-bold">
                <Icon name="lucide:log-out" class="h-4 w-4" />
                Logout
              </Button>
            </AlertDialogTrigger>

            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>Are you sure to logout?</AlertDialogTitle>
                <AlertDialogDescription>
                  You will need to authenticate again to access the application.
                </AlertDialogDescription>
              </AlertDialogHeader>

              <AlertDialogFooter>
                <AlertDialogCancel>Cancel</AlertDialogCancel>
                <AlertDialogAction @click="logOut"> Confirm </AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>
        </div>
      </div>
    </PopoverContent>
  </Popover>
</template>
